INSERT INTO AUTHOR VALUES(800, 'Tom', 'Badgeron');
INSERT INTO AUTHOR VALUES(835, 'Sun', 'Flash');
INSERT INTO AUTHOR VALUES(877, 'The', 'HoneyBadger');

INSERT INTO FLASHCARD (FLASHCARD_ID, QUESTION, ANSWER, TOPIC, AUTHOR_ID) VALUES (999, 'When do badgers sleep?', 'In the daytime', 'BEARS', 835);
INSERT INTO FLASHCARD (FLASHCARD_ID, QUESTION, ANSWER, TOPIC, AUTHOR_ID) VALUES (1003, 'Do they care?', 'NO', 'CODING', 877);
INSERT INTO FLASHCARD (FLASHCARD_ID, QUESTION, ANSWER, TOPIC, AUTHOR_ID) VALUES (1998, 'What do badgers eat?', 'Everything', 'THE_BEATLES', 835);
INSERT INTO FLASHCARD (FLASHCARD_ID, QUESTION, ANSWER, TOPIC, AUTHOR_ID) VALUES (777, 'What animal represents Hufflepuff?', 'Badger', 'CODING', 800);
INSERT INTO FLASHCARD (FLASHCARD_ID, QUESTION, ANSWER, TOPIC, AUTHOR_ID) VALUES (189, 'Of which state is the badger the state animal?', 'Wisconsin', 'THE_BEATLES', 835);

COMMIT;